#!/bin/sh
# Script by Ypnose - http://ywstd.fr

if [ "$1" = "-v" ]; then
	ARG_DIFF="u"
fi

find . -maxdepth 1 -type f | sort | while IFS=$'\n' read -r FILE; do
	if [ -f "${HOME}/.${FILE##*/}" ]; then
		diff -"${ARG_DIFF:-q}" "$FILE" "${HOME}/.${FILE##*/}"
	fi
done

exit
