#!/bin/sh
# Script by Ypnose - http://ywstd.fr

diff_found() {
	if [ -f "$1" ]; then diff -u "$1" "$2"; fi
}

find . -maxdepth 1 -type f | sort | while IFS= read -r FILE; do
	diff_found "${HOME}/.${FILE##*/}" "$FILE"
done
if [ -f "${HOME}/.ssh/config" ]; then
	(
		CONFIG_LINES="$(awk 'END{print NR}' misc/sshconfig)"
		head -n"$CONFIG_LINES" "${HOME}/.ssh/config" \
			| diff -u - misc/sshconfig
	)
fi

exit
