[font]
size = 10.5

[font.normal]
family = "Iosevka Term Custom"
style = "Medium"

[font.bold]
family = "Iosevka Term Custom"
style = "ExtraBold"

[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "#EBE4D2"
foreground = "#040404"

[colors.normal]
black = "#080808"
red = "#802E3B"
green = "#417531"
yellow = "#945D2D"
blue = "#38566C"
magenta = "#523D5D"
cyan = "#387A71"
white = "#CCB687"

[colors.bright]
black = "#404040"
red = "#951D45"
green = "#577022"
yellow = "#873411"
blue = "#324461"
magenta = "#4C3366"
cyan = "#006658"
white = "#FFE8BC"

[selection]
save_to_clipboard = false

[window.padding]
x = 10
y = 10

[env]
WINIT_X11_SCALE_FACTOR = "1.0"
